const AdminPageLocators = {
    userManagement: '.oxd-topbar-body-nav-tab-item:contains(User Management)',
    menuItems: '[role="menuitem"]',
    addUser: '[type="button"]:contains(Add)',
    userRole: '.oxd-label:contains(User Role)',
    menuList: '[role="listbox"]',
    userRoleSelect: '.oxd-select-option',
    findFieldName: '.oxd-label',
    employeeName: '.oxd-label:contains(Employee Name)',
    employeeNameInput: 'input[placeholder="Type for hints..."]',
    employeeNameSelect: '.oxd-autocomplete-option',
    status: '.oxd-label:contains(Status)',
    userName: '.oxd-label:contains(Username)',
    password: '.user-password-cell > div > div:nth-child(2) > input',
    confirmPassword: '.oxd-label:contains(Confirm)',
    saveBtn: 'button[type="submit"]',
    successMessage: '.oxd-toast--success.oxd-toast-container--toast',
    assertUserAdded: '.oxd-table-card',
    usersTableBody: '.oxd-table-body',
    searchUsername: '.oxd-label:contains(Username)',
    editIcon: '.bi-pencil-fill',
    checkUpdatedInfo: '.oxd-table-cell',
    userCheckBox: 'input[value="0"][type="checkbox"]',
    selectCheckBox: ".oxd-checkbox-input-icon",
    deleteBtn: '.oxd-button--label-danger',
    confirmDeleteBtn: '.oxd-button--medium.oxd-button--label-danger.orangehrm-button-margin',
    noRecordsFoundMessage: '.oxd-toast.oxd-toast--info',
    searchUserRole: '.oxd-label:contains(User Role)',
    resetPasswordCheckBox: '.bi-check.oxd-checkbox-input-icon',
    errorMessage: 'span.oxd-input-field-error-message',
}

export { AdminPageLocators }
